import { randomBytes, randomUUID } from "node:crypto";
import { spawnSync } from "node:child_process";
import { mkdirSync, rmSync } from "node:fs";
import { resolve } from "node:path";
import { performance } from "node:perf_hooks";
import { cpus, totalmem } from "node:os";

const adapter = process.argv.find((value) => value.startsWith("--adapter="))?.split("=", 2)[1];
if (adapter !== "sqlite-fallback" && adapter !== "postgresql-production") throw new Error("Use --adapter=sqlite-fallback or --adapter=postgresql-production.");

type Sample = { status: number; elapsedMs: number; body?: { data?: { booking?: { id: string } }; error?: { code?: string; fieldErrors?: Record<string, string[]> } } };
const percentile = (values: number[], ratio: number) => [...values].sort((a, b) => a - b)[Math.min(values.length - 1, Math.ceil(values.length * ratio) - 1)] ?? 0;
function summary(samples: Sample[], wallMs: number) {
  const times = samples.map((item) => item.elapsedMs);
  return { requests: samples.length, successes: samples.filter((item) => item.status >= 200 && item.status < 300).length, errors: samples.filter((item) => item.status >= 400).length, p50Ms: percentile(times, .5), p95Ms: percentile(times, .95), p99Ms: percentile(times, .99), maxMs: Math.max(...times), wallMs, throughputPerSecond: samples.length / (wallMs / 1000 || 1) };
}

async function postgresProduction() {
  const required = ["LOAD_BASE_URL", "LOAD_EVENT_SLUG", "LOAD_DURATION_ID", "LOAD_SECOND_EVENT_SLUG", "LOAD_SECOND_DURATION_ID", "LOAD_MISSING_EVENT_SLUG", "LOAD_MISSING_DURATION_ID", "LOAD_START_AT", "LOAD_DATABASE_URL", "LOAD_WORKER_DATABASE_URL", "LOAD_PROOF_DATABASE_URL", "LOAD_EXPECTED_APP_ROLE", "LOAD_EXPECTED_WORKER_ROLE", "LOAD_PROXY_SHARED_SECRET", "LOAD_OPERATOR_SECRET", "LOAD_EXPECTED_BUILD_ID", "LOAD_HARDWARE_LABEL"];
  if (required.some((name) => !process.env[name])) throw new Error(`PostgreSQL production load requires: ${required.join(", ")}.`);
  if (process.env.NODE_ENV !== "production" || process.env.DATABASE_PROVIDER !== "postgresql" || process.env.RATE_LIMIT_PROVIDER !== "postgresql") throw new Error("PostgreSQL production load refuses non-production or non-shared-limiter configuration.");
  const base = new URL(process.env.LOAD_BASE_URL!);
  if (!/^https:$/.test(base.protocol) && process.env.POSTGRES_INSECURE_LOCAL_TEST !== "true") throw new Error("Production load requires HTTPS except an explicit isolated local PostgreSQL proof.");
  const healthDeadline = Date.now() + 15_000; let healthReady = false;
  do {
    const health = await fetch(new URL("/api/health/ready", base), { signal: AbortSignal.timeout(3_000) }).catch(() => null);
    if (health?.ok) { healthReady = true; break; }
    await new Promise((resolve) => setTimeout(resolve, 250));
  } while (Date.now() < healthDeadline);
  if (!healthReady) throw new Error("Compiled web, PostgreSQL limiter, or dedicated worker heartbeat was not ready.");
  const operator = await fetch(new URL("/api/health/operator", base), { headers: { "x-tempocove-operator-secret": process.env.LOAD_OPERATOR_SECRET! }, signal: AbortSignal.timeout(3_000) });
  const operatorBody = await operator.json() as { appBuildId?: string; worker?: { buildId?: string } | null };
  if (!operator.ok || operatorBody.appBuildId !== process.env.LOAD_EXPECTED_BUILD_ID || operatorBody.worker?.buildId !== process.env.LOAD_EXPECTED_BUILD_ID) throw new Error("Compiled web or dedicated worker build identity did not match the expected candidate source identity.");
  const payload = { startAt: process.env.LOAD_START_AT, inviteeName: "Load Proof", inviteeEmail: `load@${process.env.LOAD_INVITEE_DOMAIN || "example.com"}`, inviteeTimeZone: "UTC", durationId: process.env.LOAD_DURATION_ID };
  async function call(key: string, body = payload, ip = "198.51.100.20", slug = process.env.LOAD_EVENT_SLUG!): Promise<Sample> { const started = performance.now(); const response = await fetch(new URL(`/api/public/${slug}/bookings`, base), { method: "POST", headers: { Origin: base.origin, "content-type": "application/json", "idempotency-key": key, "x-forwarded-for": ip, "x-tempocove-proxy-secret": process.env.LOAD_PROXY_SHARED_SECRET! }, body: JSON.stringify(body), signal: AbortSignal.timeout(10_000) }); return { status: response.status, elapsedMs: performance.now() - started, body: await response.json() as Sample["body"] }; }
  for (let i = 0; i < 10; i += 1) { const response = await fetch(new URL(`/api/public/${process.env.LOAD_EVENT_SLUG}`, base), { headers: { Origin: base.origin, "x-forwarded-for": "198.51.100.10", "x-tempocove-proxy-secret": process.env.LOAD_PROXY_SHARED_SECRET! }, signal: AbortSignal.timeout(3_000) }); if (!response.ok) { const failure = await response.json().catch(() => ({})) as { error?: { code?: string } }; throw new Error(`Production warmup failed with ${response.status}/${failure.error?.code || "UNKNOWN"}.`); } }
  const missingCredential = await call(randomUUID(), { ...payload, durationId: process.env.LOAD_MISSING_DURATION_ID }, "198.51.100.19", process.env.LOAD_MISSING_EVENT_SLUG);
  if (missingCredential.status !== 503 || missingCredential.body?.error?.code !== "GOOGLE_CALENDAR_RETRY") throw new Error(`Missing Google credential did not fail closed: ${missingCredential.status}/${missingCredential.body?.error?.code || "UNKNOWN"}.`);
  const sameSlotStarted = performance.now();
  const sameSlot = await Promise.all(Array.from({ length: 100 }, () => call(randomUUID())));
  const sameSlotWallMs = performance.now() - sameSlotStarted;
  const replayKey = randomUUID(); const replayBody = { ...payload, startAt: new Date(new Date(payload.startAt!).getTime() + 7 * 86_400_000).toISOString() }; const replayStarted = performance.now(); const replays = await Promise.all(Array.from({ length: 20 }, () => call(replayKey, replayBody, "198.51.100.21"))); const replayWallMs = performance.now() - replayStarted; const mismatched = await call(replayKey, { ...replayBody, inviteeName: "Changed body" }, "198.51.100.21");
  const winnerIds = new Set(sameSlot.flatMap((item) => item.body?.data?.booking?.id ? [item.body.data.booking.id] : [])); const replayIds = new Set(replays.flatMap((item) => item.body?.data?.booking?.id ? [item.body.data.booking.id] : []));
  const statusCounts = (items: Sample[]) => Object.fromEntries([...new Set(items.map((item) => item.status))].sort().map((status) => [status, items.filter((item) => item.status === status).length]));
  const sameSlotStatuses = statusCounts(sameSlot); const replayStatuses = statusCounts(replays);
  if (winnerIds.size !== 1 || replayIds.size !== 1 || sameSlotStatuses[201] !== 1 || sameSlotStatuses[409] !== 99 || Object.keys(sameSlotStatuses).some((status) => ![201,409].includes(Number(status))) || sameSlot.filter((item) => item.status === 409).some((item) => item.body?.error?.code !== "CONFLICT") || replays.some((item) => item.status !== 201)) {
    const safeErrors = [...sameSlot, ...replays].filter((item) => item.status >= 400).slice(0, 3).map((item) => item.body?.error);
    throw new Error(`PostgreSQL concurrency authority reconciliation failed: same-slot=${JSON.stringify(statusCounts(sameSlot))}; replay=${JSON.stringify(statusCounts(replays))}; winnerIds=${winnerIds.size}; replayIds=${replayIds.size}; errors=${JSON.stringify(safeErrors)}.`);
  }
  if (mismatched.status !== 409 || mismatched.body?.error?.code !== "CONFLICT") throw new Error("Same idempotency key with a different body was not rejected with the exact conflict contract.");
  const crossStart = new Date(new Date(payload.startAt!).getTime() + 14 * 86_400_000).toISOString(); const [tenantA, tenantB] = await Promise.all([call(randomUUID(), { ...payload, startAt: crossStart }, "198.51.100.23"), call(randomUUID(), { ...payload, startAt: crossStart, durationId: process.env.LOAD_SECOND_DURATION_ID }, "198.51.100.23", process.env.LOAD_SECOND_EVENT_SLUG)]); if (tenantA.status !== 201 || tenantB.status !== 201 || tenantA.body?.data?.booking?.id === tenantB.body?.data?.booking?.id) throw new Error("Cross-workspace independent progress failed.");
  const rateKey = randomUUID(); const rateBody = { ...payload, startAt: new Date(new Date(payload.startAt!).getTime() + 21 * 86_400_000).toISOString() }; const rate = []; for (let i = 0; i < 121; i += 1) rate.push(await call(rateKey, rateBody, "198.51.100.24")); if (rate.slice(0, 120).some((item) => item.status !== 201) || rate[120]?.status !== 429 || rate[120]?.body?.error?.code !== "RATE_LIMITED") throw new Error("Public booking rate boundary failed.");
  const sameSlotMetrics = summary(sameSlot, sameSlotWallMs); const replayMetrics = summary(replays, replayWallMs);
  if (sameSlotMetrics.p95Ms > Number(process.env.LOAD_P95_MS || 5_000) || sameSlotMetrics.p99Ms > Number(process.env.LOAD_P99_MS || 8_000)) throw new Error("Production load latency threshold failed.");
  const { Pool } = await import("pg"); const proof = new Pool({ connectionString: process.env.LOAD_PROOF_DATABASE_URL, max: 1, connectionTimeoutMillis: 3_000, statement_timeout: 3_000 }); const app = new Pool({ connectionString: process.env.LOAD_DATABASE_URL, max: 1, connectionTimeoutMillis: 3_000, statement_timeout: 3_000 }); const workerDb = new Pool({ connectionString: process.env.LOAD_WORKER_DATABASE_URL, max: 1, connectionTimeoutMillis: 3_000, statement_timeout: 3_000 });
  let queueTruth: { integration_pending: string; email_pending: string; dead: string; active_leases: string; heartbeat_fresh: boolean; heartbeat_build_id: string | null } | undefined;
  try {
    const [appIdentity, workerIdentity] = await Promise.all([app.query<{ current_user: string }>("SELECT current_user"), workerDb.query<{ current_user: string }>("SELECT current_user")]);
    if (appIdentity.rows[0]?.current_user !== process.env.LOAD_EXPECTED_APP_ROLE || workerIdentity.rows[0]?.current_user !== process.env.LOAD_EXPECTED_WORKER_ROLE || appIdentity.rows[0]?.current_user === workerIdentity.rows[0]?.current_user) throw new Error("Distinct production database role identity proof failed.");
    const ids = [...winnerIds, ...replayIds, tenantA.body!.data!.booking!.id, tenantB.body!.data!.booking!.id];
    const truth = await proof.query<{ booking_count: string; workspace_count: string; occupancy_count: string; duplicate_occupancy: string; google_provider_count: string }>('SELECT count(*)::text AS booking_count,count(DISTINCT "workspaceId")::text AS workspace_count,count(*) FILTER (WHERE "calendarProviderSnapshot"=\'google\')::text AS google_provider_count,(SELECT count(*)::text FROM "BookingOccupancy" WHERE "bookingId"=ANY($1::text[])) AS occupancy_count,(SELECT count(*)::text FROM (SELECT "workspaceId","hostId","minuteStart" FROM "BookingOccupancy" WHERE "bookingId"=ANY($1::text[]) GROUP BY 1,2,3 HAVING count(*)>1) duplicates) AS duplicate_occupancy FROM "Booking" WHERE id=ANY($1::text[])',[ids]);
    if (Number(truth.rows[0]?.booking_count) !== 4 || Number(truth.rows[0]?.workspace_count) < 2 || Number(truth.rows[0]?.google_provider_count) !== 4 || Number(truth.rows[0]?.occupancy_count) < 4 || Number(truth.rows[0]?.duplicate_occupancy) !== 0) throw new Error("PostgreSQL final booking/occupancy/provider authority reconciliation failed.");
    const queueDeadline = Date.now() + 20_000;
    do {
      const queue = await proof.query<{ integration_pending: string; email_pending: string; dead: string; active_leases: string; heartbeat_fresh: boolean; heartbeat_build_id: string | null }>('SELECT (SELECT count(*) FROM "IntegrationOutbox" WHERE "bookingId"=ANY($1::text[]) AND status IN (\'PENDING\',\'RETRY\',\'PROCESSING\'))::text AS integration_pending,(SELECT count(*) FROM "EmailOutbox" WHERE "bookingId"=ANY($1::text[]) AND status IN (\'PENDING\',\'RETRY\',\'PROCESSING\'))::text AS email_pending,((SELECT count(*) FROM "IntegrationOutbox" WHERE "bookingId"=ANY($1::text[]) AND status=\'DEAD\')+(SELECT count(*) FROM "EmailOutbox" WHERE "bookingId"=ANY($1::text[]) AND status=\'DEAD\'))::text AS dead,((SELECT count(*) FROM "IntegrationOutbox" WHERE "bookingId"=ANY($1::text[]) AND "leaseToken" IS NOT NULL)+(SELECT count(*) FROM "EmailOutbox" WHERE "bookingId"=ANY($1::text[]) AND "leaseToken" IS NOT NULL))::text AS active_leases,EXISTS(SELECT 1 FROM "WorkerHeartbeat" WHERE status IN (\'RUNNING\',\'IDLE\') AND "lastSeenAt">clock_timestamp()-interval \'30 seconds\' AND "buildId"=$2) AS heartbeat_fresh,(SELECT "buildId" FROM "WorkerHeartbeat" ORDER BY "lastSeenAt" DESC LIMIT 1) AS heartbeat_build_id',[ids,process.env.LOAD_EXPECTED_BUILD_ID]);
      queueTruth = queue.rows[0];
      if (queueTruth && Number(queueTruth.integration_pending) === 0 && Number(queueTruth.email_pending) === 0) break;
      await new Promise((resolve) => setTimeout(resolve, 250));
    } while (Date.now() < queueDeadline);
    if (!queueTruth || Number(queueTruth.integration_pending) !== 0 || Number(queueTruth.email_pending) !== 0 || Number(queueTruth.dead) !== 0 || Number(queueTruth.active_leases) !== 0 || queueTruth.heartbeat_fresh !== true || queueTruth.heartbeat_build_id !== process.env.LOAD_EXPECTED_BUILD_ID) throw new Error("Dedicated worker backlog, lease, or build reconciliation failed.");
  } finally { await Promise.all([proof.end(),app.end(),workerDb.end()]); }
  console.log(JSON.stringify({ contract: "production-path", candidateBuildId: process.env.LOAD_EXPECTED_BUILD_ID, adapter, hardware: process.env.LOAD_HARDWARE_LABEL, warmupRequests: 10, phases: { missingCredential: { requestCount: 1, status: missingCredential.status, failClosed: true }, sameSlot: { concurrency: 100, requestCount: 100, statusCounts: sameSlotStatuses, metrics: sameSlotMetrics, unexpectedErrorRate: 0 }, idempotentReplay: { concurrency: 20, requestCount: 20, statusCounts: replayStatuses, metrics: replayMetrics, oneBookingIdentity: true }, changedBody: { requestCount: 1, status: mismatched.status }, crossWorkspace: { concurrency: 2, requestCount: 2, accepted: 2 }, rateBoundary: { sequential: true, requestCount: 121, accepted: 120, rejected: 1 } }, reconciledWinnerIds: winnerIds.size, reconciledReplayIds: replayIds.size, worker: queueTruth }));
}

async function sqliteFallback() {
  const root = process.cwd(); const runtime = resolve(root, "runtime", "load"); const file = resolve(runtime, "load.db"); mkdirSync(runtime, { recursive: true });
  for (const suffix of ["", "-journal", "-shm", "-wal"]) rmSync(`${file}${suffix}`, { force: true });
  process.env.NODE_ENV = "test"; process.env.DATABASE_PROVIDER = "sqlite"; process.env.DATABASE_URL = `file:${file.replaceAll("\\", "/")}`; process.env.DEMO_MODE = "true"; process.env.DEMO_HOST_EMAIL = "load-organizer@example.invalid"; process.env.DEMO_HOST_PASSWORD = `Load!${randomBytes(18).toString("base64url")}`; process.env.AUTH_SECRET = randomBytes(32).toString("base64url"); process.env.EMAIL_TOKEN_SECRET = randomBytes(32).toString("base64url"); process.env.TOKEN_ENCRYPTION_KEY = randomBytes(32).toString("hex"); process.env.CALENDAR_PROVIDER = "local"; process.env.PAYMENTS_PROVIDER = "stub"; process.env.EMAIL_PROVIDER = "local"; process.env.OUTBOX_WORKER_MODE = "dedicated"; process.env.RATE_LIMIT_PROVIDER = "local";
  for (const [script, args] of [["node_modules/prisma/build/index.js", ["migrate", "deploy", "--schema", "prisma/schema.prisma"]], ["node_modules/tsx/dist/cli.mjs", ["prisma/seed.ts"]]] as const) { const result = spawnSync(process.execPath, [resolve(root, script), ...args], { cwd: root, env: process.env, shell: false, stdio: "ignore" }); if (result.status !== 0) throw new Error("SQLite fallback setup failed."); }
  const [{ db }, { createBooking }, { enforceRateLimit, resetRateLimitsForTest }] = await Promise.all([import("../apps/web/src/server/db.ts"), import("../apps/web/src/server/services/bookings.ts"), import("../apps/web/src/server/rate-limit.ts")]);
  const event = await db.eventType.findUniqueOrThrow({ where: { slug: "strategy-call" }, include: { durations: true } }); const duration = event.durations.find((item) => item.isDefault)!;
  const nextMonday = new Date(); nextMonday.setUTCDate(nextMonday.getUTCDate() + ((8 - nextMonday.getUTCDay()) % 7 || 7)); nextMonday.setUTCHours(15, 0, 0, 0);
  const input = { startAt: nextMonday.toISOString(), inviteeName: "Load Proof", inviteeEmail: "load@example.invalid", inviteeTimeZone: "America/Chicago", durationId: duration.id };
  async function call(key: string, body = input): Promise<Sample> { const started = performance.now(); try { const result = await createBooking("strategy-call", body, key); return { status: 201, elapsedMs: performance.now() - started, body: { data: { booking: { id: result.booking.id } } } }; } catch (error) { return { status: (error as { status?: number }).status || 409, elapsedMs: performance.now() - started, body: { error: { code: (error as { code?: string }).code } } }; } }
  const loadStarted = performance.now();
  const sameSlot = await Promise.all(Array.from({ length: 100 }, () => call(randomUUID()))); const winnerIds = new Set(sameSlot.flatMap((item) => item.body?.data?.booking?.id ? [item.body.data.booking.id] : []));
  const replayStart = new Date(nextMonday.getTime() + 7 * 86_400_000); const replayInput = { ...input, startAt: replayStart.toISOString() }; const replayKey = randomUUID(); const firstReplay = await call(replayKey, replayInput); const replays = [firstReplay, ...await Promise.all(Array.from({ length: 19 }, () => call(replayKey, replayInput)))]; const replayIds = new Set(replays.flatMap((item) => item.body?.data?.booking?.id ? [item.body.data.booking.id] : []));
  const mismatch = await call(replayKey, { ...replayInput, inviteeName: "Different body" });
  if (winnerIds.size !== 1 || replayIds.size !== 1 || replays.some((item) => item.status !== 201) || mismatch.status !== 409) throw new Error("SQLite concurrency/idempotency authority proof failed.");
  const secondUser = await db.user.create({ data: { email: "load-second@example.com", name: "Second Load Host", passwordHash: "not-used", emailVerifiedAt: new Date(), timeZone: "America/Chicago" } }); const secondWorkspace = await db.workspace.create({ data: { name: "Second Load Workspace", timeZone: "America/Chicago" } }); await db.membership.create({ data: { workspaceId: secondWorkspace.id, userId: secondUser.id, role: "OWNER" } }); const secondSchedule = await db.availabilitySchedule.create({ data: { workspaceId: secondWorkspace.id, userId: secondUser.id, timeZone: "America/Chicago" } }); await db.availabilityInterval.createMany({ data: [1,2,3,4,5].map((dayOfWeek) => ({ scheduleId: secondSchedule.id, dayOfWeek, startMinute: 540, endMinute: 1020 })) }); const secondEvent = await db.eventType.create({ data: { workspaceId: secondWorkspace.id, ownerId: secondUser.id, name: "Independent Load", slug: "independent-load", locationType: "CUSTOM", locationValue: "Local", minimumNoticeMinutes: 0 } }); const secondDuration = await db.eventDuration.create({ data: { eventTypeId: secondEvent.id, label: "30 minutes", durationMinutes: 30, isDefault: true } });
  const crossStart = new Date(nextMonday.getTime() + 14 * 86_400_000); const [crossA, crossB] = await Promise.all([call(randomUUID(), { ...input, startAt: crossStart.toISOString() }), createBooking(secondEvent.slug, { ...input, startAt: crossStart.toISOString(), durationId: secondDuration.id }, randomUUID())]); if (!crossA.body?.data?.booking?.id || !crossB.booking.id) throw new Error("SQLite cross-workspace independent progress failed.");
  const bookingRows = await db.booking.count({ where: { id: { in: [...winnerIds, ...replayIds] } } }); if (bookingRows !== 2) throw new Error("Final booking truth did not reconcile.");
  resetRateLimitsForTest(); const rateResults = await Promise.allSettled(Array.from({ length: 13 }, () => enforceRateLimit("load:public:bounded", 12, 60_000))); if (rateResults.filter((item) => item.status === "fulfilled").length !== 12) throw new Error("Local fallback rate behavior mismatch.");
  const metrics = summary([...sameSlot, ...replays], performance.now() - loadStarted); if (metrics.p95Ms > Number(process.env.LOAD_SQLITE_P95_MS || 20_000)) throw new Error("SQLite fallback p95 threshold failed.");
  console.log(JSON.stringify({ contract: "sqlite-ci-fallback-not-production-load-proof", adapter, hardware: { platform: process.platform, architecture: process.arch, cpu: cpus()[0]?.model || "unknown", logicalCpuCount: cpus().length, memoryBytes: totalmem(), node: process.version }, dataset: "100 same-slot + 20 same-idempotency + mismatch + cross-workspace + bounded local limiter", warmup: 0, metrics, reconciledBookings: bookingRows, sameSlotWinners: winnerIds.size, replayIdentities: replayIds.size, crossWorkspaceAccepted: 2, rateAccepted: 12, rateRejected: 1 }));
  await db.$disconnect();
}

await (adapter === "postgresql-production" ? postgresProduction() : sqliteFallback());
