local   all         tempocove_owner                                  scram-sha-256
local   all         all                                               reject
hostnossl all       all                 0.0.0.0/0                     reject
hostnossl all       all                 ::/0                          reject
hostssl tempocove   tempocove_owner     0.0.0.0/0                     scram-sha-256
hostssl tempocove   tempocove_owner     ::/0                          scram-sha-256
hostssl tempocove   tempocove_migration_login 0.0.0.0/0               scram-sha-256
hostssl tempocove   tempocove_migration_login ::/0                    scram-sha-256
hostssl tempocove   tempocove_app_login 0.0.0.0/0                     scram-sha-256
hostssl tempocove   tempocove_app_login ::/0                          scram-sha-256
hostssl tempocove   tempocove_worker_login 0.0.0.0/0                  scram-sha-256
hostssl tempocove   tempocove_worker_login ::/0                       scram-sha-256
hostssl tempocove   tempocove_monitor_login 0.0.0.0/0                 scram-sha-256
hostssl tempocove   tempocove_monitor_login ::/0                      scram-sha-256
hostssl all         all                 0.0.0.0/0                     reject
hostssl all         all                 ::/0                          reject
